language: php

php:
    - 5.5
    - 5.6

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --prefer-source
    - composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source

script:
    - ./vendor/bin/tester ./tests/
